### ISSUE TITLE
Add support for Mach-O file format used by Mac OS X

### ISSUE THREAD

**Issue by pragmatic** [srtkkou/zgok#1]
Please consider adding support for the [Mach-O](https://en.wikipedia.org/wiki/Mach-O) file format so Mac OS X users can enjoy this project natively too.

**Comment by srtkkou** [comment]
Thanks a lot for your suggestion. However, right now I have no experience for Mac OS, and no machine either... So sorry.

**Comment by filipochnik** [comment]
What doesn't work on macOS? Seems to work just fine for me.

**Comment by srtkkou** [comment]
Hello @filipochnik . It works in macOS? If so, it is a really good news for me. Thanks for your information! However, I still don't have the macOS machine, so I cannot guarantee if it works correctly or not.

**Comment by filipochnik** [comment]
Both manual tests and the automatic test suite pass. Maybe you can add Travis with OSX builds to this project?

**Comment by srtkkou** [comment]
@filipochnik Thanks for your comment. I fixed the travis file to test with OSX. It seems to be OK with go1.7 or later in travis OSX with my current tests. However, the tests are not really "executing" the file, so I may need to add some more better tests to really say that it is OK with OSX.

**Comment by srtkkou** [comment]
@filipochnik I added a test to build a "real" executable file (simple command to output "hello" on stdout). And also updated the test to append the zip file contents on it. Now, everything seems to be OK on travisCI with OSX. So I think I can say that this library is OK with OSX too.

**Comment by srtkkou** [comment]
I will now close this issue.
